import { GraphData } from 'src/utils/storageManager';

export const defaultCourseSystemData: GraphData = {
  nodes: [
    {
      id: 'node_0_0',
      row: 0,
      column: 0,
      rowSpan: 1,
      colSpan: 1,
      title: '高级语言程序设计',
      type: 'primary',
    },
    {
      id: 'node_1_0',
      row: 1,
      column: 0,
      rowSpan: 1,
      colSpan: 1,
      title: '高级语言程序设计实训',
      type: 'warning',
    },
    {
      id: 'node_2_0',
      row: 2,
      column: 0,
      rowSpan: 2,
      colSpan: 2,
      title: '离散数学',
      type: 'primary',
    },
    {
      id: 'node_0_1',
      row: 0,
      column: 1,
      rowSpan: 2,
      colSpan: 1,
      title: '计算机科学与技术专业导论',
      type: 'primary',
    },
    {
      id: 'node_0_2',
      row: 0,
      column: 2,
      rowSpan: 1,
      colSpan: 1,
      title: '人工智能技术',
      type: 'primary',
    },
    {
      id: 'node_1_2',
      row: 1,
      column: 2,
      rowSpan: 1,
      colSpan: 2,
      title: 'python人工智能',
      type: 'primary',
    },
    {
      id: 'node_1_2',
      row: 1,
      column: 2,
      rowSpan: 1,
      colSpan: 1,
      title: '人工智能技术',
      type: 'primary',
    },
    {
      id: 'node_4_2',
      row: 3,
      column: 2,
      rowSpan: 1,
      colSpan: 2,
      title: '数据库系统',
      type: 'primary',
      showPopup: true,
      meta: {
        info: '数据库系统是为适应数据处理的需要而发展起来的一种较为理想的数据处理系统，也是一个为实际可运行的存储、维护和应用系统提供数据的软件系统，是存储介质 、处理对象和管理系统的集合体。',
      },
    },
    {
      id: 'node_5_2',
      row: 4,
      column: 2,
      rowSpan: 1,
      colSpan: 2,
      title: '数据库系统实验',
      type: 'warning',
    },
    {
      id: 'node_4_1',
      row: 4,
      column: 1,
      rowSpan: 1,
      colSpan: 1,
      title: '数据结构与算法',
      type: 'primary',
    },
    {
      id: 'node_5_1',
      row: 5,
      column: 1,
      rowSpan: 1,
      colSpan: 1,
      title: '数据结构与算法实训',
      type: 'warning',
    },
    {
      id: 'node_0_4',
      row: 0,
      column: 4,
      rowSpan: 1,
      colSpan: 2,
      title: '面向对象程序设计(JAVA)',
      type: 'primary',
    },
    {
      id: 'node_1_4',
      row: 1,
      column: 4,
      rowSpan: 1,
      colSpan: 1,
      title: '操作系统',
      type: 'primary',
    },
    {
      id: 'node_1_5',
      row: 1,
      column: 5,
      rowSpan: 2,
      colSpan: 1,
      title: '软件工程',
      type: 'primary',
    },
    {
      id: 'node_2_4',
      row: 2,
      column: 4,
      rowSpan: 1,
      colSpan: 1,
      title: '编译原理',
      type: 'primary',
    },
    {
      id: 'node_3_5',
      row: 5,
      column: 5,
      rowSpan: 1,
      colSpan: 2,
      title: '智能终端与移动应用开发实验',
      type: 'warning',
    },
    {
      id: 'node_4_4',
      row: 4,
      column: 4,
      rowSpan: 1,
      colSpan: 1,
      title: 'WEB程序设计',
      type: 'primary',
    },
    {
      id: 'node_4_5',
      row: 4,
      column: 5,
      rowSpan: 1,
      colSpan: 1,
      title: 'WEB高级开发',
      type: 'primary',
    },
    {
      id: 'node_0_6',
      row: 0,
      column: 6,
      rowSpan: 5,
      colSpan: 2,
      title: '毕业论文',
      type: 'primary',
    },
    {
      id: 'node_5_7',
      row: 5,
      column: 7,
      rowSpan: 3,
      colSpan: 1,
      title: '企业实习',
      type: 'warning',
    },
    {
      id: 'node_6_4',
      row: 6,
      column: 4,
      rowSpan: 1,
      colSpan: 3,
      title: '软件项目开发实训',
      type: 'warning',
    },
    {
      id: 'node_0_2',
      row: 0,
      column: 2,
      rowSpan: 1,
      colSpan: 1,
      title: '人工智能技术',
      type: 'primary',
    },
    {
      id: 'node_2_3',
      row: 2,
      column: 3,
      rowSpan: 1,
      colSpan: 1,
      title: 'python人工智能实训',
      type: 'warning',
    },
  ],
  columns: [
    { id: '1', title: '第一学期' },
    { id: '2', title: '第二学期' },
    { id: '3', title: '第三学期' },
    { id: '4', title: '第四学期' },
    { id: '5', title: '第五学期' },
    { id: '6', title: '第六学期' },
    { id: '7', title: '第七学期' },
    { id: '8', title: '第八学期' },
  ],
  lines: [
    ['a_0_0_r_ox_ny', 'a_0_1_l_ox_ny'],
    ['a_2_1_t_nx_oy', 'a_1_1_b_nx_oy'],
    ['a_3_1_b_nx_oy', 'a_4_1_t_nx_oy'],
    ['a_3_1_r_ox_ny', 'a_3_2_l_ox_ny'],
    ['a_0_1_r_ox_ny', 'a_0_2_l_ox_ny'],
    ['a_0_2_r_ox_ny', 'a_0_2_r_nx_ny', 'a_1_2_tr_nx_oy'],
    ['a_1_3_b_nx_oy', 'a_2_3_t_nx_oy'],
    ['a_2_1_r_ox_ny', 'a_2_2_c_nx_ny', 'a_1_2_b_nx_oy'],
    ['a_4_1_b_nx_oy', 'a_5_1_t_nx_oy'],
    ['a_3_3_r_ox_ny', 'a_3_4_c_nx_ny', 'a_2_4_b_nx_oy'],
    ['a_2_4_t_nx_oy', 'a_1_4_b_nx_oy'],
    ['a_1_4_t_nx_oy', 'a_0_4_b_nx_oy'],
    ['a_1_5_t_nx_oy', 'a_0_5_b_nx_oy'],
    ['a_4_4_r_ox_ny', 'a_4_5_l_ox_ny'],
    ['a_4_5_r_ox_ny', 'a_4_6_l_ox_ny'],
    ['a_0_5_r_ox_ny', 'a_0_6_l_ox_ny'],
    ['a_6_6_r_ox_ny', 'a_6_7_l_ox_ny'],
    ['a_4_1_r_ox_ny', 'a_4_1_r_nx_ny', 'a_3_1_br_nx_ny', 'a_3_2_b_nx_ny', 'a_3_2_b_nx_oy'],
    ['a_3_2_br_nx_oy', 'a_4_2_tr_nx_oy'],
    ['a_3_3_b_nx_oy', 'a_3_3_b_nx_ny', 'a_3_4_b_nx_ny', 'a_4_4_t_nx_oy'],
    ['a_4_5_b_nx_oy', 'a_5_5_t_nx_oy'],
    ['a_5_6_r_ox_ny', 'a_5_7_l_ox_ny'],
    ['a_2_5_b_nx_oy', 'a_3_5_c_nx_ny', 'a_3_4_r_nx_ny', 'a_6_4_tr_nx_oy'],
    ['a_0_0_b_nx_oy', 'a_1_0_t_nx_oy'],
  ],
};

export const defaultGeoHistoryData: GraphData = {
  columns: [],
  nodes: [
    { id: 'node_0_0', row: 0, column: 0, rowSpan: 4, colSpan: 2, title: '太古宙', type: 'info' },
    { id: 'node_0_4', row: 4, column: 0, rowSpan: 5, colSpan: 2, title: '元古宙', type: 'info' },
    { id: 'node_0_9', row: 9, column: 0, rowSpan: 16, colSpan: 2, title: '显生宙', type: 'info' },
    { id: 'node_1_3', row: 3, column: 3, rowSpan: 1, colSpan: 9, title: '新太古代', type: 'info' },
    { id: 'node_1_4', row: 4, column: 3, rowSpan: 1, colSpan: 9, title: '古元古代', type: 'info' },
    { id: 'node_1_5', row: 5, column: 3, rowSpan: 1, colSpan: 9, title: '中元古代', type: 'info' },
    { id: 'node_1_6', row: 6, column: 3, rowSpan: 3, colSpan: 2, title: '新元古代', type: 'info' },
    {
      id: 'node_2_6',
      row: 6,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '青白口纪',
      type: 'primary',
    },
    { id: 'node_2_7', row: 7, column: 6, rowSpan: 1, colSpan: 6, title: '南华纪', type: 'primary' },
    { id: 'node_0_1', row: 0, column: 3, rowSpan: 1, colSpan: 9, title: '始太古代', type: 'info' },
    { id: 'node_1_1', row: 1, column: 3, rowSpan: 1, colSpan: 9, title: '古太古代', type: 'info' },
    { id: 'node_2_1', row: 2, column: 3, rowSpan: 1, colSpan: 9, title: '中太古代', type: 'info' },
    { id: 'node_8_2', row: 8, column: 6, rowSpan: 1, colSpan: 6, title: '震旦纪', type: 'primary' },
    { id: 'node_9_1', row: 9, column: 3, rowSpan: 6, colSpan: 2, title: '古生代', type: 'info' },
    { id: 'node_9_2', row: 9, column: 6, rowSpan: 1, colSpan: 6, title: '寒武纪', type: 'primary' },
    {
      id: 'node_10_2',
      row: 10,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '奥陶纪',
      type: 'primary',
    },
    {
      id: 'node_11_2',
      row: 11,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '志留纪',
      type: 'primary',
    },
    {
      id: 'node_12_2',
      row: 12,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '泥盆纪',
      type: 'primary',
    },
    {
      id: 'node_13_2',
      row: 13,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '石炭纪',
      type: 'primary',
    },
    {
      id: 'node_14_2',
      row: 14,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '二叠纪 （299～251百万年前）',
      type: 'primary',
    },
    { id: 'node_15_1', row: 15, column: 3, rowSpan: 3, colSpan: 2, title: '中生代', type: 'info' },
    { id: 'node_18_1', row: 18, column: 3, rowSpan: 7, colSpan: 2, title: '新生代', type: 'info' },
    {
      id: 'node_15_6',
      row: 15,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '三叠纪（251～199百万年前）',
      type: 'primary',
    },
    {
      id: 'node_16_6',
      row: 16,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '侏罗纪（199～145百万年前）',
      type: 'primary',
    },
    {
      id: 'node_17_6',
      row: 17,
      column: 6,
      rowSpan: 1,
      colSpan: 6,
      title: '白垩纪（145～65百万年前）',
      type: 'primary',
    },
    {
      id: 'node_18_6',
      row: 18,
      column: 6,
      rowSpan: 3,
      colSpan: 2,
      title: '古近纪',
      type: 'primary',
    },
    {
      id: 'node_21_6',
      row: 21,
      column: 6,
      rowSpan: 2,
      colSpan: 2,
      title: '新近纪',
      type: 'primary',
    },
    {
      id: 'node_23_6',
      row: 23,
      column: 6,
      rowSpan: 2,
      colSpan: 2,
      title: '第四纪',
      type: 'primary',
    },
    {
      id: 'node_18_9',
      row: 18,
      column: 9,
      rowSpan: 1,
      colSpan: 3,
      title: '古新世（65～56百万年前）',
      type: 'success',
    },
    {
      id: 'node_19_9',
      row: 19,
      column: 9,
      rowSpan: 1,
      colSpan: 3,
      title: '始新世（56～34百万年前）',
      type: 'success',
    },
    {
      id: 'node_20_9',
      row: 20,
      column: 9,
      rowSpan: 1,
      colSpan: 3,
      title: '渐新世（34～23百万年前）',
      type: 'success',
    },
    {
      id: 'node_21_9',
      row: 21,
      column: 9,
      rowSpan: 1,
      colSpan: 3,
      title: '中新世（23～5.33百万年前）',
      type: 'success',
    },
    {
      id: 'node_22_9',
      row: 22,
      column: 9,
      rowSpan: 1,
      colSpan: 3,
      title: '上新世（5.33～1.81百万年前）',
      type: 'success',
    },
    {
      id: 'node_23_9',
      row: 23,
      column: 9,
      rowSpan: 1,
      colSpan: 3,
      title: '更新世（1.81～0.01百万年前）',
      type: 'success',
    },
    {
      id: 'node_24_9',
      row: 24,
      column: 9,
      rowSpan: 1,
      colSpan: 3,
      title: '全新世（0.01百万年前～现在）',
      type: 'warning',
    },
  ],
  lines: [
    ['a_1_1_br_ox_ny', 'a_1_2_b_nx_ny', 'a_0_2_c_nx_ny', 'a_0_3_l_ox_ny'],
    ['a_1_1_br_ox_ny', 'a_1_2_b_nx_ny', 'a_1_2_c_nx_ny', 'a_1_3_l_ox_ny'],
    ['a_1_1_br_ox_ny', 'a_1_2_b_nx_ny', 'a_2_2_c_nx_ny', 'a_2_3_l_ox_ny'],
    ['a_1_1_br_ox_ny', 'a_1_2_b_nx_ny', 'a_3_2_c_nx_ny', 'a_3_3_l_ox_ny'],
    ['a_3_0_br_nx_oy', 'a_4_0_tr_nx_oy'],
    ['a_8_0_br_nx_oy', 'a_9_0_tr_nx_oy'],
    ['a_6_1_r_ox_ny', 'a_6_2_c_nx_ny', 'a_4_2_c_nx_ny', 'a_4_3_l_ox_ny'],
    ['a_6_1_r_ox_ny', 'a_6_2_c_nx_ny', 'a_5_2_c_nx_ny', 'a_5_3_l_ox_ny'],
    ['a_6_1_r_ox_ny', 'a_6_2_c_nx_ny', 'a_7_2_c_nx_ny', 'a_7_3_l_ox_ny'],
    ['a_7_4_r_ox_ny', 'a_7_5_c_nx_ny', 'a_6_5_c_nx_ny', 'a_6_6_l_ox_ny'],
    ['a_7_4_r_ox_ny', 'a_7_5_c_nx_ny', 'a_7_6_l_ox_ny'],
    ['a_7_4_r_ox_ny', 'a_7_5_c_nx_ny', 'a_8_5_c_nx_ny', 'a_8_6_l_ox_ny'],
    ['a_16_1_br_ox_ny', 'a_16_2_b_nx_ny', 'a_11_2_b_nx_ny', 'a_11_3_bl_ox_ny'],
    ['a_11_4_br_ox_ny', 'a_11_5_b_nx_ny', 'a_9_5_c_nx_ny', 'a_9_6_l_ox_ny'],
    ['a_11_4_br_ox_ny', 'a_11_5_b_nx_ny', 'a_10_5_c_nx_ny', 'a_10_6_l_ox_ny'],
    ['a_11_4_br_ox_ny', 'a_11_5_b_nx_ny', 'a_11_5_c_nx_ny', 'a_11_6_l_ox_ny'],
    ['a_11_4_br_ox_ny', 'a_11_5_b_nx_ny', 'a_12_5_c_nx_ny', 'a_12_6_l_ox_ny'],
    ['a_11_4_br_ox_ny', 'a_11_5_b_nx_ny', 'a_13_5_c_nx_ny', 'a_13_6_l_ox_ny'],
    ['a_11_4_br_ox_ny', 'a_11_5_b_nx_ny', 'a_14_5_c_nx_ny', 'a_14_6_l_ox_ny'],
    ['a_16_4_r_ox_ny', 'a_16_5_c_nx_ny', 'a_15_5_c_nx_ny', 'a_15_6_l_ox_ny'],
    ['a_16_4_r_ox_ny', 'a_16_5_c_nx_ny', 'a_16_6_l_ox_ny'],
    ['a_16_4_r_ox_ny', 'a_16_5_c_nx_ny', 'a_17_5_c_nx_ny', 'a_17_6_l_ox_ny'],
    ['a_16_1_br_ox_ny', 'a_16_2_b_nx_ny', 'a_16_2_c_nx_ny', 'a_16_3_l_ox_ny'],
    ['a_16_1_br_ox_ny', 'a_16_2_b_nx_ny', 'a_21_2_c_nx_ny', 'a_21_3_l_ox_ny'],
    ['a_21_4_r_ox_ny', 'a_21_5_c_nx_ny', 'a_19_5_c_nx_ny', 'a_19_6_l_ox_ny'],
    ['a_21_4_r_ox_ny', 'a_21_5_c_nx_ny', 'a_21_5_b_nx_ny', 'a_21_6_bl_ox_ny'],
    ['a_21_4_r_ox_ny', 'a_21_5_c_nx_ny', 'a_23_5_b_nx_ny', 'a_23_6_bl_ox_ny'],
    [],
    ['a_19_7_r_ox_ny', 'a_19_8_c_nx_ny', 'a_18_8_c_nx_ny', 'a_18_9_l_ox_ny'],
    ['a_19_7_r_ox_ny', 'a_19_8_c_nx_ny', 'a_19_9_l_ox_ny'],
    ['a_19_7_r_ox_ny', 'a_19_8_c_nx_ny', 'a_20_8_c_nx_ny', 'a_20_9_l_ox_ny'],
    ['a_21_7_br_ox_ny', 'a_21_8_b_nx_ny', 'a_21_8_c_nx_ny', 'a_21_9_l_ox_ny'],
    ['a_21_7_br_ox_ny', 'a_21_8_b_nx_ny', 'a_22_8_c_nx_ny', 'a_22_9_l_ox_ny'],
    ['a_23_7_br_ox_ny', 'a_23_8_b_nx_ny', 'a_23_8_c_nx_ny', 'a_23_9_l_ox_ny'],
    ['a_23_7_br_ox_ny', 'a_23_8_b_nx_ny', 'a_24_8_c_nx_ny', 'a_24_9_l_ox_ny'],
    ['a_15_8_br_nx_oy', 'a_16_8_tr_nx_oy'],
    ['a_18_10_b_nx_oy', 'a_19_10_t_nx_oy'],
    ['a_19_10_b_nx_oy', 'a_20_10_t_nx_oy'],
    ['a_20_10_b_nx_oy', 'a_21_10_t_nx_oy'],
    ['a_21_10_b_nx_oy', 'a_22_10_t_nx_oy'],
    ['a_22_10_b_nx_oy', 'a_23_10_t_nx_oy'],
    ['a_23_10_b_nx_oy', 'a_24_10_t_nx_oy'],
    ['a_16_8_br_nx_oy', 'a_17_8_tr_nx_oy'],
    ['a_17_6_br_nx_oy', 'a_18_6_tr_nx_oy'],
    ['a_20_6_br_nx_oy', 'a_21_6_tr_nx_oy'],
    ['a_22_6_br_nx_oy', 'a_23_6_tr_nx_oy'],
    ['a_13_8_br_nx_oy', 'a_14_8_tr_nx_oy'],
    ['a_14_8_br_nx_oy', 'a_15_8_tr_nx_oy'],
    ['a_0_7_b_nx_oy', 'a_1_7_t_nx_oy'],
    ['a_1_7_b_nx_oy', 'a_2_7_t_nx_oy'],
    ['a_2_7_b_nx_oy', 'a_3_7_t_nx_oy'],
    ['a_3_7_b_nx_oy', 'a_4_7_t_nx_oy'],
    ['a_4_7_b_nx_oy', 'a_5_7_t_nx_oy'],
    ['a_5_3_br_nx_oy', 'a_6_3_tr_nx_oy'],
    ['a_6_8_br_nx_oy', 'a_7_8_tr_nx_oy'],
    ['a_7_8_br_nx_oy', 'a_8_8_tr_nx_oy'],
    ['a_8_8_br_nx_oy', 'a_9_8_tr_nx_oy'],
    ['a_9_8_br_nx_oy', 'a_10_8_tr_nx_oy'],
    ['a_10_8_br_nx_oy', 'a_11_8_tr_nx_oy'],
    ['a_11_8_br_nx_oy', 'a_12_8_tr_nx_oy'],
    ['a_12_8_br_nx_oy', 'a_13_8_tr_nx_oy'],
  ],
};
